### ISSUE TITLE
Home Page isn't displayed on Firefox

### ISSUE THREAD

**Issue by caike08** [BancoTalentosTCC/BancoTalentosTCC#26]
If I am displaying any other screen, except from the home one, and I decide to go back to my root / page, somehow the page isn't displayed on Firefox, as you can see in the screenshot below:

![screenshot from 2016-07-06 01 52 26](https://cloud.githubusercontent.com/assets/4422230/16607879/98c86b00-431c-11e6-9fe4-a7f9387b9b6f.png)

The error isn't noticed on Chrome.

**Comment by MarceloBorgesP** [comment]
I think it might have been fixed when we switched our router for Flow Router. I was checking this here now and seems to be working great!
