### ISSUE TITLE
Encrypt password when log in, make login form redirect users to Main Panel

### ISSUE THREAD

**Issue by caike08** [BancoTalentosTCC/BancoTalentosTCC#38]

**Comment by MarceloBorgesP** [comment]
Actually the password is already encrypted by the [meteor-accounts](https://guide.meteor.com/accounts.html) package when the new user is registered.

If you want to see this working, you can register a new user and type `ctrl + m` and check the database, you will see the user account with its password with md5 encryption

**Comment by caike08** [comment]
I see, I see. So we should fix just when the user tries to log in through the sign in screen, it is possible to see its password, as you can see in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/4422230/16846245/fff2a358-49c1-11e6-97ba-2671c62d130b.png)

**Comment by MarceloBorgesP** [comment]
I think I didn't understand what you meant here, could you explain better? Where is it possible to see the user's password?

**Comment by caike08** [comment]
Somehow, this was fixed in your last Pull Request. So I'm closing this one.
