### ISSUE TITLE
Send verification email when either a student or a company are included

### ISSUE THREAD

**Issue by caike08** [BancoTalentosTCC/BancoTalentosTCC#44]
So far, we allow students and companies to include an email without verification. It allows them to use non existent emails to have access in our system. This shouldn't be allowed, as we may use their own email to handle forgotten passwords and further notifications.

To avoid it, it is necessary to implement a process to validate their email when it's created. I found two links that may be useful to solve this issue:

https://themeteorchef.com/snippets/sign-up-with-email-verification/
https://themeteorchef.com/snippets/using-the-email-package

Ps: it's likely to have an email registered to our application. So we need to check whether we will use an existing one, based on third part services like Google, Microsoft, or we will use a local one registered into our server.

**Comment by MarceloBorgesP** [comment]
Fixed on #79
